# Generated by Django 6.1.2 on 2026-10-09 00:43

import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('nepali_name', models.CharField(blank=True, default='', max_length=200)),
                ('barcode', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('cost_price', models.FloatField(default=0.0)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('min_stock_threshold', models.IntegerField(default=5)),
                ('unit', models.CharField(blank=True, default='pcs', max_length=16)),
                ('industry_mode', models.CharField(blank=True, default='RETAIL', max_length=32)),
                ('destination_route', models.CharField(blank=True, default='', max_length=255)),
                ('is_kitchen_item', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('api_key', models.CharField(default=shop.models.generate_api_key, max_length=80, unique=True)),
                ('pan_vat', models.CharField(blank=True, default='', max_length=64)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('currency', models.CharField(blank=True, default='रू', max_length=8)),
                ('vat_rate', models.FloatField(default=13.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField(blank=True, null=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=64)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('subtotal', models.FloatField(default=0.0)),
                ('discount_total', models.FloatField(default=0.0)),
                ('service_charge', models.FloatField(default=0.0)),
                ('vat_tax_amount', models.FloatField(default=0.0)),
                ('grand_total', models.FloatField(default=0.0)),
                ('payment_method', models.CharField(blank=True, db_index=True, default='CASH', max_length=32)),
                ('payment_status', models.CharField(blank=True, default='', max_length=64)),
                ('transaction_ref', models.CharField(blank=True, default='', max_length=128)),
                ('industry_mode', models.CharField(blank=True, default='RETAIL', max_length=32)),
                ('meta_info', models.CharField(blank=True, default='', max_length=255)),
                ('items_summary', models.TextField(blank=True, default='')),
                ('cash_tendered', models.FloatField(default=0.0)),
                ('cash_change', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='shop.store')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SaleLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('product_id_external', models.BigIntegerField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('list_price', models.FloatField(default=0.0)),
                ('unit_price', models.FloatField(default=0.0)),
                ('line_total', models.FloatField(default=0.0)),
                ('cost_total', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('passenger_type', models.CharField(blank=True, default='Regular', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_lines', to='shop.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='shop.saletransaction')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_lines', to='shop.store')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.store'),
        ),
        migrations.AddConstraint(
            model_name='saletransaction',
            constraint=models.UniqueConstraint(fields=('store', 'invoice_number'), name='unique_invoice_per_store'),
        ),
    ]
